In [2]:
import torch
import numpy as np

In [5]:
np_data = np.arange(15).reshape(3, 5)
np_data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
torch_data = torch.arange(15).reshape(3, 5)
torch_data

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [7]:
torch_data1 = torch.from_numpy(np_data)
torch_data1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [8]:
data = torch.Tensor(3, 5)
data

tensor([[6.0847e-19, 0.0000e+00, 6.0847e-19, 0.0000e+00, 6.0845e-19],
        [0.0000e+00, 6.0854e-19, 0.0000e+00, 5.9866e-19, 0.0000e+00],
        [5.9867e-19, 0.0000e+00, 5.9868e-19, 0.0000e+00, 5.9868e-19]])

In [9]:
data1 = torch.rand(5, 3)
data1

tensor([[0.6287, 0.9441, 0.0089],
        [0.5665, 0.4664, 0.0384],
        [0.5314, 0.2927, 0.2569],
        [0.0796, 0.3813, 0.4031],
        [0.3627, 0.3032, 0.2533]])